require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.gitsigns")
require("user.autopairs")
require("user.comment")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.indentline")
-- require "user.alpha"
require("user.whichkey")
require("user.autocommands")
require("user.nvim-tree")

require("user.leap")
require("user.persistence")
require("user.trouble")
require("user.todo-comments")
require("user.lsp-colors")
require("user.wilder")
require("user.zk-nvim")
require("user.harpoon")
require("user.undotree")
-- require "user.git-worktree"
-- require "user.notify"
-- require "user.noice"
require("user.zen-mode")
require("user.twilight")
require("user.typescript-nvim")
require("user.nvim-highlight-colors")
require("user.nvim-lastplace")
