# `nix fmt` runs treefmt across the whole tree. Adds:
#   - alejandra for *.nix
#   - stylua for *.lua
#   - shfmt for *.sh
#   - prettier for *.md, *.json, *.yaml, *.yml
{inputs, ...}: {
  imports = [inputs.treefmt-nix.flakeModule];

  perSystem = _: {
    treefmt = {
      projectRootFile = "flake.nix";

      programs = {
        alejandra.enable = true;
        stylua.enable = true;
        shfmt.enable = true;
        prettier.enable = true;
      };

      # `flake.nix` is auto-generated by `nix run .#write-flake` (vic/flake-file).
      # alejandra would reformat it on every commit, then write-flake reformats
      # it back on the next regeneration — a churn loop. flake-file's emitted
      # form is canonical for the generated file.
      settings.global.excludes = ["flake.nix"];
    };
  };
}
