# callPackage helper: takes the evaluated `nvim.*` config from the aggregator
# and produces a wrapped nvim derivation. No home-manager, no NixOS — just
# `wrapNeovimUnstable` over the bare binary plus a synthesized bootstrap.
{
  lib,
  neovim-unwrapped,
  wrapNeovimUnstable,
  neovimUtils,
  vimUtils,
  symlinkJoin,
  writeTextFile,
  plugins,
  extraPackages,
  extraLuaConfig,
  colorscheme,
  spineLua,
  withNodeJs,
  withPython3,
  withRuby,
}: let
  spineFiles = lib.mapAttrsToList (name: content:
    writeTextFile {
      name = "nvim-spine-${name}";
      text = content;
      destination = "/lua/_spine_${name}.lua";
    })
  spineLua;

  spinePlugin = vimUtils.buildVimPlugin {
    pname = "nvim-experimental-spines";
    version = "0";
    src = symlinkJoin {
      name = "nvim-experimental-spines-src";
      paths = spineFiles;
    };
  };

  spineRequires =
    lib.concatMapStringsSep "\n"
    (name: ''pcall(require, "_spine_${name}")'')
    (lib.attrNames spineLua);

  bootstrap = ''
    -- Experimental nvim wrapper bootstrap.
    -- Generated by modules/programs/neovim-experimental/_wrapper.nix.

    ${extraLuaConfig}

    -- Spines (synthesized; see modules/programs/neovim-experimental/lib/<name>/).
    ${spineRequires}

    ${lib.optionalString (colorscheme != null) ''
      pcall(function() vim.cmd.colorscheme("${colorscheme}") end)
    ''}
  '';

  allPlugins =
    plugins
    ++ lib.optional (spineLua != {}) {plugin = spinePlugin;};

  nvimConfig = neovimUtils.makeNeovimConfig {
    inherit withNodeJs withPython3 withRuby;
    plugins = allPlugins;
    customRC = ''
      lua << EOF
      ${bootstrap}
      EOF
    '';
  };
in
  wrapNeovimUnstable neovim-unwrapped (nvimConfig
    // {
      wrapperArgs =
        nvimConfig.wrapperArgs
        ++ lib.optionals (extraPackages != []) [
          "--prefix"
          "PATH"
          ":"
          "${lib.makeBinPath extraPackages}"
        ];
    })
